"""slots.bin -> weights.h, the same bytes the trainer wrote.

THE BLOB IS NOT RE-DERIVED HERE. It is `slots.bin` verbatim, split into the
per-head offsets the device indexes with, because a second implementation of the
file format is a second place for it to be wrong. The header carries the byte
count and the bucket width so the sketch can assert against them rather than
assume.
"""
import struct, sys

HEAD_CLASSES = [2, 3, 5, 4, 4, 5]          # gate tool audience price when intent


def main(src="../slots.bin", dst="slots_device/weights.h"):
    with open(src, "rb") as f:
        buckets, nheads = struct.unpack("<II", f.read(8))
        if nheads != len(HEAD_CLASSES):
            sys.exit(f"{src}: {nheads} heads, expected {len(HEAD_CLASSES)}")
        blob, offs = bytearray(), []
        for h, want in enumerate(HEAD_CLASSES):
            nc, _pad = struct.unpack("<II", f.read(8))
            if nc != want:
                sys.exit(f"{src}: head {h} has {nc} classes, expected {want}")
            offs.append(len(blob))
            blob += f.read(buckets * nc)

    with open(dst, "w") as o:
        o.write(f"/* GENERATED by weights_header.py from {src} - do not edit. */\n")
        o.write(f"#define W_BUCKETS {buckets}u\n")
        o.write(f"#define W_BYTES   {len(blob)}u\n")
        o.write("static const uint32_t HEAD_OFF[6] = {%s};\n" % ",".join(map(str, offs)))
        o.write("static const int8_t WEIGHTS[] PROGMEM = {\n")
        for i in range(0, len(blob), 32):
            o.write(",".join(str(b - 256 if b > 127 else b) for b in blob[i:i + 32]) + ",\n")
        o.write("};\n")
    print(f"{dst}: {buckets} buckets, {len(blob):,} bytes ({len(blob)/1024:.1f} KiB)")


if __name__ == "__main__":
    main(*sys.argv[1:])
